/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Conexion.Database;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul
 */
public class login_Gerente extends javax.swing.JFrame {

    static String rut_gerente;
    static home home = new home();
    /**
     * Creates new form login_Admin
     */
    public login_Gerente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblenunciao = new javax.swing.JLabel();
        btn_volver = new javax.swing.JButton();
        btningresar = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        lblPassAdmin = new javax.swing.JLabel();
        txtrut = new javax.swing.JTextField();
        lblRutAdmin = new javax.swing.JLabel();
        lblFondoLoginA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesion: ADMINISTRADOR");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblenunciao.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lblenunciao.setForeground(new java.awt.Color(255, 255, 255));
        lblenunciao.setText("Inicio de sesión Gerencia");
        getContentPane().add(lblenunciao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 410, 40));

        btn_volver.setBackground(new java.awt.Color(255, 255, 255));
        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        getContentPane().add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 73, -1));

        btningresar.setBackground(new java.awt.Color(0, 153, 153));
        btningresar.setText("Ingresar");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        getContentPane().add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 30));

        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpassKeyTyped(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, 30));

        lblPassAdmin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblPassAdmin.setText("Ingrese Contraseña:");
        getContentPane().add(lblPassAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtrut.setName(""); // NOI18N
        txtrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutActionPerformed(evt);
            }
        });
        txtrut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutKeyTyped(evt);
            }
        });
        getContentPane().add(txtrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 30));

        lblRutAdmin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRutAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblRutAdmin.setText("Ingrese Rut:");
        getContentPane().add(lblRutAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lblFondoLoginA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home.jpg"))); // NOI18N
        lblFondoLoginA.setText("jLabel1");
        getContentPane().add(lblFondoLoginA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        
        String rut1 = txtrut.getText();
        rut_gerente = rut1;
        String clave1 = txtpass.getText();
        
        
        if(txtrut.getText().equals("") && txtpass.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese Credenciales correctas", "Aviso", JOptionPane.ERROR_MESSAGE);
        }else if(txtrut.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese Rut porfavor", "Aviso", JOptionPane.ERROR_MESSAGE);
        }else if(txtpass.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese Contraseña porfavor", "Aviso", JOptionPane.ERROR_MESSAGE);
        }else{
            try {
 
            String rut = txtrut.getText();
            String clave = txtpass.getText();
            
            String rutsinDigito = rut.substring(0,rut.length()-1);
            String rutDigito =rut.substring(rut.length()-1);  
            String rutFinal = rutsinDigito+"-"+rutDigito;
            
            int coincidencia = 0;
            
            ResultSet lista = Database.crearConsulta("SELECT * FROM gerente WHERE run='" + rutFinal + "' and clave='" + clave + "'");

            while (lista.next()) {
                coincidencia = coincidencia + 1;
            }

            if (coincidencia == 0) { //Si no encontró algo
                JOptionPane.showMessageDialog(null, "No se encuentra usuario", "Aviso", JOptionPane.ERROR_MESSAGE);
            } else if (coincidencia >= 1) {
                        JOptionPane.showMessageDialog(null, "Login exitoso");
                        home.dispose();
                        new vista_Gerente().setVisible(true);
                        this.dispose();
                    }
        } catch (Exception e) {
            System.out.println(e);
        }
        }
        
        
        
        
    }//GEN-LAST:event_btningresarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_volverActionPerformed

    private void txtrutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutKeyTyped
           // TODO add your handling code here:
           int maximorut=9;
           int errores=0;
           char validarCaracter=evt.getKeyChar();
           ArrayList<Character> lista=retornarListaCaracteres();
           
           for (int i = 0; i < lista.size(); i++) {
               char caracter = lista.get(i);
               if(validarCaracter==caracter ){
               errores= errores+1;
               }
           }
           
           if((Character.isLetter(validarCaracter)&& validarCaracter != 'k') || txtrut.getText().length()>=maximorut || errores > 0 ){
                    evt.consume();
           }
            
    }//GEN-LAST:event_txtrutKeyTyped

    private void txtpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyTyped
        // TODO add your handling code here:
        int maximorut=20;
        
        if(txtpass.getText().length()>=maximorut){
        evt.consume();
        }
    }//GEN-LAST:event_txtpassKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_volver;
    private javax.swing.JButton btningresar;
    private javax.swing.JLabel lblFondoLoginA;
    private javax.swing.JLabel lblPassAdmin;
    private javax.swing.JLabel lblRutAdmin;
    private javax.swing.JLabel lblenunciao;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtrut;
    // End of variables declaration//GEN-END:variables

    private static class btn_volver {

    }
    
    private ArrayList<Character> retornarListaCaracteres(){
        ArrayList<Character> validaciones = new ArrayList<Character>();
           validaciones.add('.');
           validaciones.add('/');
           validaciones.add('|');
           validaciones.add('=');
           validaciones.add('?');
           validaciones.add('¿');
           validaciones.add('´');
           validaciones.add('¨');
           validaciones.add('{');
           validaciones.add('}');
           validaciones.add(';');
           validaciones.add(':');
           validaciones.add('_');
           validaciones.add('^');
           validaciones.add('-');
           validaciones.add('!');
           validaciones.add('"');
           validaciones.add('#');
           validaciones.add('$');
           validaciones.add('%');
           validaciones.add('&');
           validaciones.add('(');
           validaciones.add(')');
           validaciones.add('¡');
           validaciones.add(']');
           validaciones.add('*');
           validaciones.add('[');
           validaciones.add(',');
           validaciones.add('°');
        return  validaciones;
    }
    
    

    
    
}
