/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Conexion.Database;
import Clases.Oferta;
import java.awt.List;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vina
 */
public class vista_crearOferta extends javax.swing.JFrame {
    static home home = new home();
    static login_Admin l_Admin = new login_Admin();
    
    ArrayList<Oferta> ofertas = new ArrayList<Oferta>();
    Database cn;
    Connection reg;

    /**
     * Creates new form agregarOferta
     */
    public vista_crearOferta() {
        initComponents();
        mostrarProductos();
        cn = new Database();
        reg = cn.getConnection();
        

    }
    
    public void mostrarProductos(){
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rs = Database.crearConsulta("SELECT * FROM producto");
        modelo.setColumnIdentifiers(new Object[]{"SKU","NOMBRE","DESCRIPCION","CATEGORIA","MARCA"});
        try{
            while(rs.next()){
                modelo.addRow(new Object[]{rs.getString("sku"),rs.getString("nombre"),rs.getString("descripcion"),rs.getString("categoria_id"),rs.getString("marca_id")});
            }
            tblProductos.setModel(modelo);
            
        }catch(Exception e){
            System.out.println("Error: "+e);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTexto1 = new javax.swing.JLabel();
        txtDatos = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JLabel();
        txtDescrip = new javax.swing.JLabel();
        txtInicioO = new javax.swing.JLabel();
        txtTerminoO = new javax.swing.JLabel();
        txtPrecioNormal = new javax.swing.JLabel();
        txtPrecioOferta = new javax.swing.JLabel();
        txtComMin = new javax.swing.JLabel();
        txtComMax = new javax.swing.JLabel();
        tfTitulo = new javax.swing.JTextField();
        tfDescrip = new javax.swing.JTextField();
        tfPrecioNor = new javax.swing.JTextField();
        tfPrecioOfer = new javax.swing.JTextField();
        tdCantiMin = new javax.swing.JTextField();
        tfCantMax = new javax.swing.JTextField();
        btnCrearOferta = new javax.swing.JButton();
        dcOp1 = new com.toedter.calendar.JDateChooser();
        dcOp2 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        btn_salir = new javax.swing.JButton();
        btn_ofertas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CREAR OFERTA");

        txtTexto1.setText("Lista de productos");

        txtDatos.setText("Ingrese datos de la oferta:");

        txtTitulo.setText("Titulo:");

        txtDescrip.setText("Descripción:");

        txtInicioO.setText("Fecha inicio de la oferta:");

        txtTerminoO.setText("Fecha termino de la oferta:");

        txtPrecioNormal.setText("Precio normal de la oferta");

        txtPrecioOferta.setText("Precio de la oferta:");

        txtComMin.setText("Compra minima por producto");

        txtComMax.setText("Compra maxima por producto");

        btnCrearOferta.setText("Crear oferta");
        btnCrearOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearOfertaActionPerformed(evt);
            }
        });

        dcOp1.setDateFormatString("yyyy-MM-dd");

        dcOp2.setDateFormatString("yyyy-MM-dd");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "sku", "nombre", "descripcion", "categoria_id", "marca_id"
            }
        ));
        jScrollPane2.setViewportView(tblProductos);

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_ofertas.setText("Ver Ofertas");
        btn_ofertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ofertasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCrearOferta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_ofertas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtComMin)
                                            .addComponent(txtComMax))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tdCantiMin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfCantMax, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDescrip)
                                            .addComponent(txtInicioO)
                                            .addComponent(txtTerminoO))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dcOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dcOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfPrecioNor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfPrecioOfer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtTitulo)
                                    .addComponent(txtPrecioNormal)
                                    .addComponent(txtPrecioOferta)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(txtDatos)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTexto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescrip)
                    .addComponent(tfDescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtInicioO)
                    .addComponent(dcOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTerminoO)
                    .addComponent(dcOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioNormal)
                    .addComponent(tfPrecioNor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioOferta)
                    .addComponent(tfPrecioOfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComMin)
                    .addComponent(tdCantiMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComMax)
                    .addComponent(tfCantMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearOferta)
                    .addComponent(btn_salir)
                    .addComponent(btn_ofertas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearOfertaActionPerformed
        
        
        int ultimoId =0;      
        String fechaI = "";
        String fechaT = "";
        Date dateI = null; 
        Date dateT = null; 
        String titulo = tfTitulo.getText();
        String descrip = tfDescrip.getText();

        try {
        dateI = dcOp1.getDate(); 
        dateT = dcOp2.getDate(); 
        fechaI = dateI.toString();
        fechaT = dateT.toString();
        }
        catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Ingrese fecha valida.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        String precioNormal = tfPrecioNor.getText();
        String precioOferta = tfPrecioOfer.getText();
        String cantMin = tdCantiMin.getText();
        String cantMax = tfCantMax.getText();
        
        int itemSeleccionado = tblProductos.getSelectedColumn();
        System.out.println(tblProductos.getSelectedRow());
        //System.out.println(tblProductos.getValueAt(tblProductos.getSelectedRow(), 0));
        String idProducto = String.valueOf(tblProductos.getValueAt(tblProductos.getSelectedRow(), 0));
        System.out.println(idProducto);
        
        if(itemSeleccionado<=0){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un producto.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }else{
            
            if(titulo.length()==0 || descrip.length()==0 || fechaI.length()==0 || fechaT.length()==0 || 
                    precioNormal.length()==0 || precioOferta.length()==0 || cantMin.length()==0 || cantMax.length()==0){
                JOptionPane.showMessageDialog(this, "Llene los datos correctamente.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }else{
                ArrayList<Object> ofertas = new ArrayList<Object>();
                PreparedStatement pst=null;
                PreparedStatement insOferProd=null;
                PreparedStatement coleccionOfertas=null;
                java.sql.Date sqlFechaInicio = new java.sql.Date(dateI.getTime());         
                java.sql.Date sqlFechaTermino = new java.sql.Date(dateT.getTime());   
                try{
                    coleccionOfertas=reg.prepareStatement("SELECT * FROM oferta");   
                    ResultSet lista = coleccionOfertas.executeQuery();
                    while (lista.next())  //recorre
                    {
                     ultimoId=lista.getInt(1);
                    }
                    ultimoId=ultimoId+1;
                    
                    
                    pst=reg.prepareStatement("INSERT INTO oferta VALUES(?,?,?,?,?,?,?,?,?,?)");
                    if(ultimoId==0){
                        ultimoId=1;
                    }
                    pst.setInt(1, ultimoId);
                    pst.setString(2, titulo);   
                    pst.setString(3, descrip);
                    pst.setDate(4, sqlFechaInicio);
                    pst.setDate(5, sqlFechaTermino);
                    pst.setInt(6, Integer.parseInt(precioNormal));
                    pst.setInt(7, Integer.parseInt(precioOferta));
                    pst.setInt(8, Integer.parseInt(cantMin));
                    pst.setInt(9, Integer.parseInt(cantMax));
                    pst.setInt(10, 0);
                    int i=pst.executeUpdate();
                    if(i>0){
                        System.out.println("Se guardo correctamente");
                        JOptionPane.showMessageDialog(this,"Oferta guardada correctamente.");
                        tfTitulo.setText("");
                        tfDescrip.setText("");
                        dcOp1.setDate(null);
                        dcOp2.setDate(null);
                        tfPrecioNor.setText("");
                        tfPrecioOfer.setText("");
                        tdCantiMin.setText("");
                        tfCantMax.setText("");
                        
                        insOferProd=reg.prepareStatement("INSERT INTO oferta_producto VALUES(?,?)");
                        insOferProd.setInt(1, ultimoId);
                        insOferProd.setString(2, idProducto);
                        insOferProd.executeUpdate();
                                       
                    }else{
                        System.out.println("No se guardo");
                        JOptionPane.showMessageDialog(this, "Error al guardar datos.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    
                }catch(Exception e){
                
                }
                
            }
        }
        
        
        
    }//GEN-LAST:event_btnCrearOfertaActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
        home.setVisible(true);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_ofertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ofertasActionPerformed
        new verOfertas().setVisible(true);
    }//GEN-LAST:event_btn_ofertasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearOferta;
    private javax.swing.JButton btn_ofertas;
    private javax.swing.JButton btn_salir;
    private com.toedter.calendar.JDateChooser dcOp1;
    private com.toedter.calendar.JDateChooser dcOp2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField tdCantiMin;
    private javax.swing.JTextField tfCantMax;
    private javax.swing.JTextField tfDescrip;
    private javax.swing.JTextField tfPrecioNor;
    private javax.swing.JTextField tfPrecioOfer;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JLabel txtComMax;
    private javax.swing.JLabel txtComMin;
    private javax.swing.JLabel txtDatos;
    private javax.swing.JLabel txtDescrip;
    private javax.swing.JLabel txtInicioO;
    private javax.swing.JLabel txtPrecioNormal;
    private javax.swing.JLabel txtPrecioOferta;
    private javax.swing.JLabel txtTerminoO;
    private javax.swing.JLabel txtTexto1;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
