/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Conexion.Database;
import Clases.*;
import Tablas.*;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raul
 */
public class vista_Consumidores extends javax.swing.JFrame {
    static home login = new home();
    
    Tabla_Consumidor tc = new Tabla_Consumidor();    
    Limpiar lim = new Limpiar();    
    CRUDconsumidor crud_cons;
    int clic_tabla = 0;
    
    /**
     * Creates new form listaProductos
     */
    public vista_Consumidores() {
        initComponents();
        tc.visualizar_Consumidor(tab_consumidores);
        
        Comuna comuna = new Comuna();
        comuna.mostrarComuna(cb_comuna);
        
        activa_boton(true,false,false,true);
    }
    
    public void agregar(){
        crud_cons = new CRUDconsumidor();
        Consumidor cons = new Consumidor();
        
        cons.setRun(txt_rut.getText());
        cons.setP_nombre(txt_nombre1.getText());
        cons.setS_nombre(txt_nombre2.getText());
        cons.setApellido_p(txt_apellido1.getText());
        cons.setApellido_m(txt_apellido2.getText());
        cons.setEmail(txt_email.getText());
        cons.setClave(txt_password.getText());
        cons.setPuntaje(Integer.parseInt(txt_puntaje.getText()));
        if(chk_activo.isSelected()){
            cons.setActivo('1');
        } else{
            cons.setActivo('0');
        }
        if(chk_suscrito.isSelected()){
            cons.setSuscrito('1');
        } else{
            cons.setSuscrito('0');
        }
        cons.setComuna_id(Integer.parseInt(lbl_comuna_id.getText()));
        
        crud_cons.Agregar_Consumidor(cons);
    }
    
    //Metodo eliminar producto
    public void modificar(){
        crud_cons = new CRUDconsumidor();
        Consumidor cons = new Consumidor();
        
        cons.setP_nombre(txt_nombre1.getText());
        cons.setS_nombre(txt_nombre2.getText());
        cons.setApellido_p(txt_apellido1.getText());
        cons.setApellido_m(txt_apellido2.getText());
        cons.setEmail(txt_email.getText());
        cons.setClave(txt_password.getText());
        cons.setPuntaje(Integer.parseInt(txt_puntaje.getText()));
        if(chk_activo.isSelected()){
            cons.setActivo('1');
        } else{
            cons.setActivo('0');
        }
        if(chk_suscrito.isSelected()){
            cons.setSuscrito('1');
        } else{
            cons.setSuscrito('0');
        }
        cons.setComuna_id(Integer.parseInt(lbl_comuna_id.getText()));
        cons.setRun(txt_rut.getText());
        
        crud_cons.Modificar_Consumidor(cons);
    }
    
    //Metodo eliminar producto
    public void eliminar(){
        crud_cons = new CRUDconsumidor();
        Consumidor cons = new Consumidor();
        
        cons.setRun(txt_rut.getText());
        
        crud_cons.Eliminar_Consumidor(cons);
    }
    
    public void activa_boton(boolean a1, boolean a2, boolean a3, boolean a4){
        btn_agregar.setEnabled(a1);
        btn_modificar.setEnabled(a2);
        btn_eliminar.setEnabled(a3);
        txt_rut.setEnabled(a4);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab_consumidores = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        btn_agregar = new javax.swing.JButton();
        lbl_clave = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JLabel();
        txt_apellido2 = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_nombre1 = new javax.swing.JTextField();
        txt_rut = new javax.swing.JTextField();
        lbl_rut = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        lbl_activo = new javax.swing.JLabel();
        txt_nombre2 = new javax.swing.JTextField();
        txt_apellido1 = new javax.swing.JTextField();
        chk_activo = new javax.swing.JCheckBox();
        lbl_comuna = new javax.swing.JLabel();
        cb_comuna = new javax.swing.JComboBox<>();
        lbl_comuna_id = new javax.swing.JLabel();
        lbl_suscrito = new javax.swing.JLabel();
        chk_suscrito = new javax.swing.JCheckBox();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_puntaje = new javax.swing.JLabel();
        txt_puntaje = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consumidores");

        tab_consumidores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_consumidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_consumidoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_consumidores);

        btn_agregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        lbl_clave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_clave.setText("Clave:");

        lbl_apellidos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_apellidos.setText("Apellidos:");

        txt_nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre1ActionPerformed(evt);
            }
        });

        lbl_rut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_rut.setText("RUT");

        lbl_nombres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_nombres.setText("Nombres:");

        btn_modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        lbl_activo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_activo.setText("Activo:");

        chk_activo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chk_activo.setSelected(true);
        chk_activo.setText("SI/NO");
        chk_activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_activoActionPerformed(evt);
            }
        });

        lbl_comuna.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_comuna.setText("Comuna:");

        cb_comuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_comunaActionPerformed(evt);
            }
        });

        lbl_suscrito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_suscrito.setText("Suscrito:");

        chk_suscrito.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chk_suscrito.setSelected(true);
        chk_suscrito.setText("SI/NO");
        chk_suscrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_suscritoActionPerformed(evt);
            }
        });

        lbl_email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_email.setText("Email:");

        lbl_puntaje.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_puntaje.setText("Puntaje:");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_limpiar))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_rut)
                            .addComponent(lbl_nombres))
                        .addGap(10, 10, 10)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(txt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_nombre1))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(lbl_puntaje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_puntaje))
                            .addComponent(txt_nombre2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_clave)
                            .addComponent(lbl_comuna))
                        .addGap(15, 15, 15)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_password)
                            .addComponent(cb_comuna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(lbl_activo)
                                .addGap(18, 18, 18)
                                .addComponent(chk_activo))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(lbl_suscrito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_suscrito))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_apellidos)
                            .addComponent(lbl_email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_comuna_id)
                                .addGap(14, 14, 14))
                            .addComponent(txt_email)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addComponent(txt_apellido1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_rut)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_puntaje)
                        .addComponent(txt_puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_nombres)
                        .addComponent(txt_nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_nombre1))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_apellidos)
                        .addComponent(txt_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_clave)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_activo)
                    .addComponent(chk_activo))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_comuna)
                        .addComponent(cb_comuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_suscrito)
                        .addComponent(chk_suscrito)))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_limpiar))
                .addGap(20, 20, 20)
                .addComponent(lbl_comuna_id))
        );

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        agregar();
        tc.visualizar_Consumidor(tab_consumidores);
        activa_boton(true,false,false,true);
        lim.limpiar_texto(panel);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre1ActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        modificar();
        tc.visualizar_Consumidor(tab_consumidores);
        activa_boton(true,false,false,false);
        lim.limpiar_texto(panel);
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        int s = JOptionPane.showConfirmDialog(null, "Eliminar consumidor","Si/no",JOptionPane.YES_NO_OPTION);
        if(s == 0){
            eliminar();
            tc.visualizar_Consumidor(tab_consumidores);
            activa_boton(true,false,false,true);
            lim.limpiar_texto(panel);
        }

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        lim.limpiar_texto(panel);
        activa_boton(true,false,false,true);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void tab_consumidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_consumidoresMouseClicked
        clic_tabla = this.tab_consumidores.rowAtPoint(evt.getPoint());
        
        String run = ""+tab_consumidores.getValueAt(clic_tabla, 0);
        String p_nombre = ""+tab_consumidores.getValueAt(clic_tabla, 1);
        String s_nombre = ""+tab_consumidores.getValueAt(clic_tabla, 2);
        String apellido_p = ""+tab_consumidores.getValueAt(clic_tabla, 3);
        String apellido_m = ""+tab_consumidores.getValueAt(clic_tabla, 4);
        String email = ""+tab_consumidores.getValueAt(clic_tabla, 5);
        String clave = ""+tab_consumidores.getValueAt(clic_tabla, 6);
        int puntaje = (int)tab_consumidores.getValueAt(clic_tabla, 7);
        String activoStr = ""+tab_consumidores.getValueAt(clic_tabla, 8);
        char activo;
        if(activoStr.equals("Si")){
            activo = '1';
        }else{
            activo = '0';
        }
       // char activo = (char)tab_consumidores.getValueAt(clic_tabla, 8);
        String suscritoStr = ""+tab_consumidores.getValueAt(clic_tabla, 9);
        char suscrito;
        if(suscritoStr.equals("Si")){
            suscrito = '1';
        }else{
            suscrito = '0';
        }
       // char suscrito = (char)tab_consumidores.getValueAt(clic_tabla, 9);
        int comuna_id = (int)tab_consumidores.getValueAt(clic_tabla, 10);
        
        txt_rut.setText(run);
        txt_nombre1.setText(p_nombre);
        txt_nombre2.setText(s_nombre);
        txt_apellido1.setText(apellido_p);
        txt_apellido2.setText(apellido_m);
        txt_email.setText(email);
        txt_password.setText(clave);
        txt_puntaje.setText(""+puntaje);
        
        if(activo == '1'){
            chk_activo.setSelected(true);
        }else {
            chk_activo.setSelected(false);
        }
        if(suscrito == '1'){
            chk_suscrito.setSelected(true);
        }else {
            chk_suscrito.setSelected(false);
        }
        cb_comuna.setSelectedIndex(1);
        
        int column = tab_consumidores.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tab_consumidores.getRowHeight();
        
        if(row < tab_consumidores.getRowCount() && row >= 0 && column < tab_consumidores.getColumnCount() && column >= 0){
            Object value = tab_consumidores.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;

                if(boton.getName().equals("mod")){
                    System.out.println("Click en el boton modificar");
                    //EVENTOS MODIFICAR
                    activa_boton(true,true,false,false);
                }
                if(boton.getName().equals("eli")){
                    //JOptionPane.showConfirmDialog(null, "Desea eliminar este registro", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    System.out.println("Click en el boton eliminar");
                    //EVENTOS ELIMINAR
                    activa_boton(true,false,true,true);
                }
            }

        }
    }//GEN-LAST:event_tab_consumidoresMouseClicked

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        new vista_Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void chk_activoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_activoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_activoActionPerformed

    private void cb_comunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_comunaActionPerformed
        lbl_comuna_id.hide();
        lbl_comuna_id.setText(""+cb_comuna.getItemAt(cb_comuna.getSelectedIndex()).getId());
    }//GEN-LAST:event_cb_comunaActionPerformed

    private void chk_suscritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_suscritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_suscritoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<Comuna> cb_comuna;
    private javax.swing.JCheckBox chk_activo;
    private javax.swing.JCheckBox chk_suscrito;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_activo;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_clave;
    private javax.swing.JLabel lbl_comuna;
    private javax.swing.JLabel lbl_comuna_id;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_puntaje;
    private javax.swing.JLabel lbl_rut;
    private javax.swing.JLabel lbl_suscrito;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tab_consumidores;
    private javax.swing.JTextField txt_apellido1;
    private javax.swing.JTextField txt_apellido2;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_nombre2;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_puntaje;
    private javax.swing.JTextField txt_rut;
    // End of variables declaration//GEN-END:variables
}
