/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.GeneradorMail;
import Conexion.Database;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.mail.*;

/**
 *
 * @author Raul
 */
public class vista_Admin extends javax.swing.JFrame {

    static home login = new home();
    static vista_Consumidores cons = new vista_Consumidores();
    /**
     * Creates new form vista_Admin
     */
    public vista_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblenunciao = new javax.swing.JLabel();
        btnConsumidor = new javax.swing.JButton();
        btnEncargados = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnEmpresasRetail = new javax.swing.JButton();
        btnEmpresasSucursal = new javax.swing.JButton();
        btnReporteBI = new javax.swing.JButton();
        btnMail = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        fondoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRADOR");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblenunciao.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lblenunciao.setForeground(new java.awt.Color(255, 255, 255));
        lblenunciao.setText("Menu Administración");
        lblenunciao.setAlignmentX(0.5F);
        lblenunciao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblenunciao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblenunciao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 50));

        btnConsumidor.setBackground(new java.awt.Color(204, 204, 204));
        btnConsumidor.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btnConsumidor.setText("Consumidores");
        btnConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsumidorActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsumidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 265, 38));

        btnEncargados.setBackground(new java.awt.Color(204, 204, 204));
        btnEncargados.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btnEncargados.setText("Encargados");
        btnEncargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncargadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncargados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 265, 38));

        btnProductos.setBackground(new java.awt.Color(204, 204, 204));
        btnProductos.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 265, 40));

        btnEmpresasRetail.setBackground(new java.awt.Color(204, 204, 204));
        btnEmpresasRetail.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btnEmpresasRetail.setText("Empresas: Retail");
        btnEmpresasRetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresasRetailActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpresasRetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 265, 40));

        btnEmpresasSucursal.setBackground(new java.awt.Color(204, 204, 204));
        btnEmpresasSucursal.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btnEmpresasSucursal.setText("Empresas: Sucursal");
        btnEmpresasSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresasSucursalActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpresasSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 265, 40));

        btnReporteBI.setText("Obtener reporte");
        btnReporteBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteBIActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporteBI, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        btnMail.setText("Enviar correos");
        btnMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMailActionPerformed(evt);
            }
        });
        getContentPane().add(btnMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 70, -1));

        fondoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAdmin.jpg"))); // NOI18N
        getContentPane().add(fondoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsumidorActionPerformed
        new vista_Consumidores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsumidorActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btnEncargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncargadosActionPerformed
        new vista_Encargados().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEncargadosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        new vista_Productos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnEmpresasRetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresasRetailActionPerformed
        new vista_EmpresasRetail().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmpresasRetailActionPerformed

    private void btnEmpresasSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresasSucursalActionPerformed
        new vista_EmpresasSucursal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmpresasSucursalActionPerformed

    private void btnMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMailActionPerformed
        
            GeneradorMail gm = new GeneradorMail();
        try {
            gm.EnviarEmail();
        } catch (IOException ex) {
            Logger.getLogger(vista_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_btnMailActionPerformed

    private void btnReporteBIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteBIActionPerformed
        try {
            crearReporteBI();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(vista_Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(vista_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReporteBIActionPerformed

    private void crearReporteBI() throws FileNotFoundException, DocumentException {
        
        Document documento = new Document();
        
        
        File desktopDir = new File(System.getProperty("user.home"), "Desktop");
        System.out.println(desktopDir.getPath() + " " + desktopDir.exists());
        String pathToDesktop = desktopDir.getPath();
        //FileOutputStream out =  new FileOutputStream(new File(pathToDesktop+System.getProperty("file.separator")+"pdf de prueba.pdf"));
        PdfWriter.getInstance(documento, new FileOutputStream(new File(pathToDesktop+System.getProperty("file.separator")+"Reporte historial.pdf")));
        
        documento.open();
        documento.add(new Paragraph("Descripción de actividad de los clientes"));
        

        Database cnOfertas = new Database();
        Database cnConsumidor = new Database();
        int contador = 0;

        String sqlBI = "select * from comportamiento_bi where rut_consumidor like ?";
        ResultSet listaBI = null;
        PreparedStatement psBI = null;

        String sqlConsu = "select run,p_nombre,apellido_p from consumidor";
        ResultSet listaConsu = null;
        PreparedStatement psConsu = null;
        
        String sqlOfertas = "select titulo from oferta WHERE id = ?";
        ResultSet listaOfertas = null;
        PreparedStatement psOfertas = null;
        
        /*
        String sqlEvaluacion = "select * from evaluacion WHERE id = ?";
        ResultSet listaEvaluacion = null;
        PreparedStatement psEvaluacion = null;
        */
        String rut_consumidor="";
        String nombreConsumidor="";
        String info="Sin movimientos";
        String info2="";
    
    
    
    /**
     * @param args the command line arguments
     */
        try {

            psConsu = cnConsumidor.getConnection().prepareStatement(sqlConsu);
            listaConsu = psConsu.executeQuery();

            com.itextpdf.text.Font dataRedFont = FontFactory.getFont(FontFactory.TIMES_ROMAN, 14, BaseColor.RED);
            Paragraph p = new Paragraph();

            Paragraph p3 = new Paragraph();
            documento.add(new Paragraph("--------------------------------------------------"));
            documento.add(new Paragraph(" "));
            documento.add(p);
            com.itextpdf.text.Font dataBlackFont = FontFactory.getFont("Garamond", 13, BaseColor.BLACK);

            while (listaConsu.next()) {

                rut_consumidor = listaConsu.getString(1);  //obtener el rut de cada consumidor en el loop
                nombreConsumidor = listaConsu.getString(2) + " " + listaConsu.getString(3);;

                psBI = cnOfertas.getConnection().prepareStatement(sqlBI);
                psBI.setString(1, rut_consumidor);
                listaBI = psBI.executeQuery();

                Paragraph p2 = new Paragraph();
                p2.add(new Chunk(info, dataBlackFont));

                Paragraph p1 = new Paragraph();
                p1.add(new Chunk(rut_consumidor, dataBlackFont));

                while (listaBI.next()) {

                    String rutCons = listaBI.getString(3);

                    com.itextpdf.text.Font dataBlueFont = FontFactory.getFont(FontFactory.TIMES_ROMAN, 14, BaseColor.BLUE);
                    com.itextpdf.text.Font dataBoldFont = FontFactory.getFont(FontFactory.TIMES_BOLD, 14, BaseColor.BLACK);

                    psOfertas = cnOfertas.getConnection().prepareStatement(sqlOfertas);
                    psOfertas.setInt(1, listaBI.getInt(2));

                    listaOfertas = psOfertas.executeQuery();
                    info2 = "";

                    while (listaOfertas.next()) {
                        if (info.equals("Sin movimientos")) {
                            p2.clear();
                        }

                        info = listaOfertas.getString(1) + " visto " + listaBI.getInt(4) + " veces;";

                    }
                    if (!info.equals("Sin movimientos")) {
                        p2.add(new Chunk(info, dataBlackFont));
                    }

                    p3.add(new Chunk("sin info", dataBlackFont));

                    info2 = rutCons;

                }
                documento.add(p1);
                documento.add(p2);

                //     p2.clear();
                info = "Sin movimientos";

                documento.add(new Paragraph(" "));
            }

            JOptionPane.showMessageDialog(this, "Documento creado en el escritorio con nombre *Reporte historial*.");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error al crear el documento.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Error al crear el documento.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } finally {
        }
        documento.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsumidor;
    private javax.swing.JButton btnEmpresasRetail;
    private javax.swing.JButton btnEmpresasSucursal;
    private javax.swing.JButton btnEncargados;
    private javax.swing.JButton btnMail;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnReporteBI;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel fondoAdmin;
    private javax.swing.JLabel lblenunciao;
    // End of variables declaration//GEN-END:variables
}
