/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.GeneradorMail;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.mail.*;

/**
 *
 * @author Raul
 */
public class vista_Admin extends javax.swing.JFrame {

    static home login = new home();
    static vista_Consumidores cons = new vista_Consumidores();
    /**
     * Creates new form vista_Admin
     */
    public vista_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblenunciao = new javax.swing.JLabel();
        btnConsumidor = new javax.swing.JButton();
        btnEncargados = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnEmpresasRetail = new javax.swing.JButton();
        btnEmpresasSucursal = new javax.swing.JButton();
        btnMail = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        fondoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRADOR");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblenunciao.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lblenunciao.setForeground(new java.awt.Color(255, 255, 255));
        lblenunciao.setText("Menu Administración");
        lblenunciao.setAlignmentX(0.5F);
        lblenunciao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblenunciao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblenunciao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 50));

        btnConsumidor.setBackground(new java.awt.Color(204, 204, 204));
        btnConsumidor.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btnConsumidor.setText("Consumidores");
        btnConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsumidorActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsumidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 265, 38));

        btnEncargados.setBackground(new java.awt.Color(204, 204, 204));
        btnEncargados.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btnEncargados.setText("Encargados");
        btnEncargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncargadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEncargados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 265, 38));

        btnProductos.setBackground(new java.awt.Color(204, 204, 204));
        btnProductos.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 265, 40));

        btnEmpresasRetail.setBackground(new java.awt.Color(204, 204, 204));
        btnEmpresasRetail.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btnEmpresasRetail.setText("Empresas: Retail");
        btnEmpresasRetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresasRetailActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpresasRetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 265, 40));

        btnEmpresasSucursal.setBackground(new java.awt.Color(204, 204, 204));
        btnEmpresasSucursal.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btnEmpresasSucursal.setText("Empresas: Sucursal");
        btnEmpresasSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresasSucursalActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpresasSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 265, 40));

        btnMail.setText("Enviar correos");
        btnMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMailActionPerformed(evt);
            }
        });
        getContentPane().add(btnMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 70, -1));

        fondoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoAdmin.jpg"))); // NOI18N
        getContentPane().add(fondoAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsumidorActionPerformed
        new vista_Consumidores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsumidorActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btnEncargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncargadosActionPerformed
        new vista_Encargados().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEncargadosActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        new vista_Productos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnEmpresasRetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresasRetailActionPerformed
        new vista_EmpresasRetail().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmpresasRetailActionPerformed

    private void btnEmpresasSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresasSucursalActionPerformed
        new vista_EmpresasSucursal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmpresasSucursalActionPerformed

    private void btnMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMailActionPerformed
        
            GeneradorMail gm = new GeneradorMail();
        try {
            gm.EnviarEmail();
        } catch (IOException ex) {
            Logger.getLogger(vista_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_btnMailActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsumidor;
    private javax.swing.JButton btnEmpresasRetail;
    private javax.swing.JButton btnEmpresasSucursal;
    private javax.swing.JButton btnEncargados;
    private javax.swing.JButton btnMail;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel fondoAdmin;
    private javax.swing.JLabel lblenunciao;
    // End of variables declaration//GEN-END:variables
}
